title: year-progress
name: year-progress
base: core24
version: '0.0.4'
summary: Year Progress
contact: ivofernandes12@gmail.com
issues: https://github.com/ivoxavier/year-progress/issues
website: https://github.com/ivoxavier/year-progress/
license: GPL-3.0-only
description: |
  A super fast application built with Vala and GTK4 for GNOME.

grade: stable
confinement: strict 


slots:
  dbus-year-progress:
    interface: dbus
    bus: session
    name: com.ixsvf.yearprogress

apps:
  year-progress:
    command: usr/bin/year-progress
    extensions: [gnome]
    common-id: com.ixsvf.yearprogress.desktop 
    slots: [dbus-year-progress]

parts:
  year-progress:
    plugin: meson
    source: .
    meson-parameters:
      - --prefix=/usr
    build-packages:
      - valac
      - libgtk-4-dev
      - gettext
