title: year-progress
name: year-progress
base: core24
version: '0.0.6'
summary: Year Progress
contact: ivofernandes12@gmail.com
issues: https://github.com/ivoxavier/year-progress/issues
website: https://github.com/ivoxavier/year-progress/
icon: data/com.ixsvf.yearprogress.svg
license: GPL-3.0-only
donation: https://www.paypal.com/donate/?hosted_button_id=EZUYCD4ANT4RA
description: |
  A super fast application built with Vala and GTK4 for GNOME.

grade: stable
confinement: strict 

slots:
  dbus-year-progress:
    interface: dbus
    bus: session
    name: com.ixsvf.yearprogress

apps:
  year-progress:
    command: usr/bin/year-progress
    extensions: [gnome]
    common-id: com.ixsvf.yearprogress.desktop
    desktop: meta/gui/com.ixsvf.yearprogress.desktop 
    slots: [dbus-year-progress]

parts:
  year-progress:
    plugin: meson
    source: .
    meson-parameters:
      - --prefix=/usr
    build-packages:
      - valac
      - libgtk-4-dev
      - gettext
    override-build: |
      
      craftctl default
      
      
      mkdir -p $CRAFT_PART_INSTALL/meta/gui
      cp $CRAFT_PART_SRC/data/com.ixsvf.yearprogress.desktop $CRAFT_PART_INSTALL/meta/gui/
      cp $CRAFT_PART_SRC/data/com.ixsvf.yearprogress.svg $CRAFT_PART_INSTALL/meta/gui/
      
      
      sed -i 's|^Icon=.*|Icon=${SNAP}/meta/gui/com.ixsvf.yearprogress.svg|g' $CRAFT_PART_INSTALL/meta/gui/com.ixsvf.yearprogress.desktop
      rm -f $CRAFT_PART_INSTALL/usr/share/applications/com.ixsvf.yearprogress.desktop
